# Generated by Django 6.0.1 on 2026-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('pickup_date', models.DateField()),
                ('plastic_kg', models.FloatField(default=0)),
                ('metal_kg', models.FloatField(default=0)),
                ('glass_kg', models.FloatField(default=0)),
                ('wood_kg', models.FloatField(default=0)),
                ('trash_kg', models.FloatField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
