# Generated by Django 5.2.6 on 2026-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='landmark',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='state',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
